set(PROJECT_ICO ${CMAKE_SOURCE_DIR}/rsc/igal_qt.ico)

set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_VENDOR "Amsostudios.com")

set(CPACK_NSIS_MUI_ICON ${PROJECT_ICO})
set(CPACK_NSIS_INSTALLED_ICON_NAME ${PROJECT_ICO})
set(CPACK_NSIS_MENU_LINKS "bin/${PROJECT_NAME}.exe" "${PROJECT_NAME}")	

set(CPACK_IFW_PACKAGE_ICON ${PROJECT_ICO})

set(CPACK_PACKAGE_INSTALL_DIRECTORY "${PROJECT_NAME}")

set(CPACK_IFW_PACKAGE_TITLE "${PROJECT_NAME}")
set(CPACK_IFW_PACKAGE_PUBLISHER "ien@amsostudios.com")
set(CPACK_IFW_PACKAGE_ALLOW_SPACE_IN_PATH OFF)

include(CPack)